/** Categorías precargadas para publicaciones en la tienda (géneros y tipos de colección). Incluir "Otros" al final. */
export const TIENDA_CATEGORIAS = [
    'Figuras y estatuas',
    'Funko Pop y similares',
    'Juguetes y figuras de acción',
    'Coleccionables cine y TV',
    'Anime y manga',
    'Comics y tebeos',
    'Coleccionables de videojuegos',
    'Cartas (TCG / CCG / deportivas)',
    'Juegos de mesa y miniaturas',
    'LEGO y construcción',
    'Modelismo y dioramas',
    'Coches a escala',
    'Dados, pins y llaveros',
    'Ropa y merchandising',
    'Cómics y arte firmado',
    'Música y vinilos',
    'Deportes y memorabilia',
    'Colección vintage',
    'Colección retro',
    'Colección limitada / exclusivos',
    'Juegos y puzzles',
    'Cómics y novelas gráficas',
    'Colección infantil',
    'Otros',
]
